/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "VIS"
include(
    ":general:MyProtocol",
    ":socket:java:Hello",
    ":socket:java:Echo_SocketServer",
    ":socket:java:Echo_SocketClient",
    ":socket:java:Demo_SocketClient",
    ":servlet:PrimitiveServlet",
    ":servlet:DemoServlet",
    ":socket:cpp:Hello",
    ":socket:cpp:Primitive_SocketClient",
    ":socket:cpp:Primitive_SocketServer",
    ":socket:cpp:Demo_SocketServer")
